version: '3'

services:
  nginx:
    build: ./requirements/nginx/
    container_name: nginx
    image: nginx
    ports:
      - 443:443
    env_file:
      - .env
    networks:
      - inception_network
    volumes:
      - wdp_data:/var/www/html
    depends_on:
      - wordpress
    restart: always
  mariadb:
    build: ./requirements/mariadb/
    container_name: mariadb
    image: mariadb
    env_file:
      - .env
    networks:
      - inception_network
    volumes:
      - db_data:/var/lib/mysql
    restart: always

  wordpress:
    build: ./requirements/wordpress/
    container_name: wordpress
    image: wordpress
    env_file:
      - .env
    networks:
      - inception_network
    volumes:
      - wdp_data:/var/www/html
    depends_on:
      - mariadb
    restart: always

networks:
  inception_network:
    driver: bridge

volumes:
  wdp_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/imad/imimouni/data/wp
  db_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/imad/imimouni/data/db
